lamguage: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-946710816238"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
